// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knufcrejuzwetgstjpzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudWZjcmVqdXp3ZXRnc3RqcHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzI3NDIsImV4cCI6MjA1OTM0ODc0Mn0.hPuw1Ydqa5jWIIu7chmatDBymM0WuigSiL7tT42qLL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: window.sessionStorage
  }
});

// Export Database and Tables types for use in the app
export type { Database } from './types';
